# -*- coding: utf-8 -*-
"""CR-Task-1-Python-Intern-Anand-Yadav.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GoNKL5g6WwL6LXoU0g0A_jbognmTBCRj

# **TO-DO List Application using Python**
"""

import csv
import os
from datetime import datetime

# File to store tasks
file_path = 'todo_list.csv'

# Function to initialize the CSV file
def initialize_file():
    if not os.path.exists(file_path):
        with open(file_path, 'w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(["Task", "Priority", "Due Date", "Status"])

# Function to add a task
def add_task(task, priority, due_date):
    with open(file_path, 'a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow([task, priority, due_date, "Pending"])

# Function to remove a task
def remove_task(task):
    tasks = []
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        tasks = list(reader)
    with open(file_path, 'w', newline='') as file:
        writer = csv.writer(file)
        for row in tasks:
            if row[0] != task:
                writer.writerow(row)

# Function to mark a task as completed
def complete_task(task):
    tasks = []
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        tasks = list(reader)
    with open(file_path, 'w', newline='') as file:
        writer = csv.writer(file)
        for row in tasks:
            if row[0] == task:
                row[3] = "Completed"
            writer.writerow(row)

# Function to display tasks
def display_tasks():
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header
        for row in reader:
            print(f"Task: {row[0]}, Priority: {row[1]}, Due Date: {row[2]}, Status: {row[3]}")

# Main function
def main():
    initialize_file()
    while True:
        print("\nTo-Do List Application")
        print("1. Add Task")
        print("2. Remove Task")
        print("3. Mark Task as Completed")
        print("4. View Tasks")
        print("5. Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            task = input("Enter task description: ")
            priority = input("Enter task priority (high, medium, low): ")
            due_date = input("Enter due date (YYYY-MM-DD): ")
            add_task(task, priority, due_date)
        elif choice == '2':
            task = input("Enter task description to remove: ")
            remove_task(task)
        elif choice == '3':
            task = input("Enter task description to mark as completed: ")
            complete_task(task)
        elif choice == '4':
            print("\nTo-Do List:")
            display_tasks()
        elif choice == '5':
            print("Exiting To-Do List Application. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()